services:
  tools:
    image: ${IMAGE_REGISTRY-docker.io}/${IMAGE_ORG-weshigbee}/tools-net # at a minimum tools for network spelunking (i.e. dns, nics, etc)
    build:
      context: .
      platforms:
        - "linux/arm64"
        - "linux/amd64"
