name: tools-net

on:
  workflow_dispatch: # manually too
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          # LATER push here too:
          # with:
          #   registry: ghcr.io
          #   username: ${{ github.actor }}
          #   password: ${{ secrets.GITHUB_TOKEN }}

# Notes
#   docker actions: https://github.com/marketplace?category=&type=&verification=&query=publisher%3Adocker
