name: tools-net

on:
  workflow_dispatch: # manually too
  push:
    branches:
      - master
    paths:
      - "tools-net/**"
      - ".github/workflows/tools-net.yml"
      # filter cheat sheet: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

concurrency: # one-at-a-time (one pending, one running)
  cancel-in-progress: true # cancel the one running
  group: ${{ github.workflow }}-push-image # limit on the image that is being pushed
  # fav docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

# Runner Images: https://github.com/actions/runner-images (what is pre-installed on the runner)
#   FYI => open workflow run => pick a job => Set up job => Runner Image
#     => Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240422.1/images/ubuntu/Ubuntu2204-Readme.md
#     => Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240422.1

jobs:
  build:
    runs-on: [ubuntu-latest]
    environment: push-images # to require review - docs https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    steps:

      # *** SETUP EXPECTED BUILD ENV ***
      #   philosohpy: what should be available (i.e. installed, configured) in any build env
      - uses: actions/checkout@v4 # fav docs: https://github.com/marketplace/actions/checkout
      - uses: docker/setup-buildx-action@v3 # https://github.com/marketplace/actions/docker-setup-buildx
      #   for multi-arch builds
      - run: docker buildx ls # dump avail builders
      - uses: docker/login-action@v3 # fav docs: https://github.com/marketplace/actions/docker-login
        # rationale: could move to script, however b/c this step is linked to secrets, I lean toward keeping it here to reduce risk of leaking secrets in the script, thus expected env is to be already authenticated to registry.
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      # *** HAND OFF TO BUILD SCRIPT ***
      #   use script to reproduce/troubleshoot locally, push complexity here
      - run: ./build-push.sh
        env:
          IMAGE_REGISTRY: docker.io
        working-directory: tools-net

      # *** SWITCH BUILD ENV to LOGIN to GHCR ***
      - uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - run: ./build-push.sh
        env:
          IMAGE_REGISTRY: ghcr.io
        working-directory: tools-net


# Notes
#   docker actions: https://github.com/marketplace?category=&type=&verification=&query=publisher%3Adocker
#   vscode extension rocks (actions are linked to versioned (tagged) docs pages) - also yaml, EditorConfig
#
# actions:
#   setup-docker https://github.com/marketplace/actions/setup-docker
#   build/push https://github.com/marketplace/actions/build-and-push-docker-images
#   docker/setup-qemu-action@v3 # i.e. test multi-arch builds # https://github.com/marketplace/actions/docker-setup-qemu
#
#
# *** unused/alternate actions ***
#   # if I want tag generation then I can add that to build script where it is easier to troubleshoot and reproducible locally (prefer shared, composable scripts for reuse)
#   - id: meta
#     uses: docker/metadata-action@v5 # fav docs: https://github.com/marketplace/actions/docker-metadata-action
#     with:
#       images: |
#         weshigbee/tools-net
#       labels: |
#         maintainer=g0t4
#         org.opencontainers.image.title=networking-tools
#         org.opencontainers.image.description=Common networking tools - i.e. ip, ping, dig, nslookup, etc
#         org.opencontainers.image.licenses=MIT
#   - run:
#       echo ${{ steps.meta.outputs.json }}
#       # PRN other image names and/or tagging config
