name: tools-net

on:
  workflow_dispatch: # manually too
  push:
    branches:
      - master
    paths:
      - "tools-net/**"
      - ".github/workflows/tools-net.yml"
      # filter cheat sheet: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

concurrency: # one-at-a-time
  cancel-in-progress: true
  group: ${{ github.workflow }}-push-image # limit on the image that is being pushed
  # fav docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

jobs:
  build:
    runs-on: [ubuntu-latest]
    environment: push-images # to require review - docs https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    steps:
      - uses: actions/checkout@v4 # fav docs: https://github.com/marketplace/actions/checkout
      # gonna stick w/ compose build for now
      # - id: meta
      #   uses: docker/metadata-action@v5 # fav docs: https://github.com/marketplace/actions/docker-metadata-action
      #   with:
      #     images: |
      #       weshigbee/tools-net
      #     labels: |
      #       maintainer=g0t4
      #       org.opencontainers.image.title=networking-tools
      #       org.opencontainers.image.description=Common networking tools - i.e. ip, ping, dig, nslookup, etc
      #       org.opencontainers.image.licenses=MIT
      # - run:
      #     echo ${{ steps.meta.outputs.json }}
      #     # PRN other image names and/or tagging config
      - uses: docker/login-action@v3 # fav docs: https://github.com/marketplace/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          # LATER: registry: ghcr.io / {{ github.actor }} {{ secrets.GITHUB_TOKEN }}

      # PRN setup-docker https://github.com/marketplace/actions/setup-docker
      # PRN https://github.com/marketplace/actions/build-and-push-docker-images

      - uses: docker/setup-buildx-action@v3 # https://github.com/marketplace/actions/docker-setup-buildx
      # PRN use docker compose to build and push
      - run: docker buildx ls # PRN buildx setup
      - run: docker compose build --pull --push # as expected: Multi-platform build is not supported for the docker driver
        working-directory: tools-net

      # FYI uses: docker/setup-qemu-action@v3 # i.e. test multi-arch builds # https://github.com/marketplace/actions/docker-setup-qemu
# Notes
#   docker actions: https://github.com/marketplace?category=&type=&verification=&query=publisher%3Adocker
#   vscode extension rocks (actions are linked to versioned (tagged) docs pages) - also yaml, EditorConfig
